site_name: ollama_apps
site_url: https://chaitu-ycr.github.io/ollama_apps/
site_description: "ollama apps. python based apps."
site_author: chaitu-ycr

repo_name: chaitu-ycr/ollama_apps
repo_url: https://github.com/chaitu-ycr/ollama_apps
edit_uri: blob/main/docs/

nav:
  - Overview: index.md
  - src_manual: src_manual.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            show_docstring_modules: false
  - include-markdown:
      recursive: true
  - macros
  - search

theme:
  name: readthedocs
  features:
    - toc.integrate
    - search

extra_css:
  - _assets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.10.0/dist/mermaid.min.js
